In [2]:
#Arrays
import numpy

In [3]:
x = numpy.zeros( [3, 3] )
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
x[0,0] = 1
x[1,1] = 5
x[2,2] = 6
x[2,0] = 2
x[0,2] = 3
print(x)

[[1. 0. 3.]
 [0. 5. 0.]
 [2. 0. 6.]]


In [5]:
y = x[0,2]
print(y)

3.0


In [6]:
x[3,3]

IndexError: index 3 is out of bounds for axis 0 with size 3