In [1]:
#Arrays
import numpy

In [2]:
x = numpy.zeros( [3, 3] )
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
x[0,0] = 1
x[1,1] = 5
x[2,2] = 6
x[2,0] = 2
x[0,2] = 3
print(x)

[[1. 0. 3.]
 [0. 5. 0.]
 [2. 0. 6.]]
